---
##templateモジュールで、設定ファイルをコピーする。
##DBのIPアドレス/ドメイン欄に変数を置いており、そこにRDSのドメインが入る。

- name: Configure phpMyAdmin1 "/etc/httpd/conf.d/phpMyAdmin.conf"
  template:
    src: phpMyAdmin.conf
    dest: "{{ phpmyadmin1_dest }}"
    owner: root
    group: root
    mode: 0644

- name: Configure phpMyAdmin2 "/etc/phpMyAdmin/config.inc.php"
  template:
    src: config.inc.php
    dest: "{{ phpmyadmin2_dest }}"
    owner: root
    group: root
    mode: 0644
