---
##templateモジュールで、設定ファイルをコピーする。
##DBのIPアドレス/ドメイン欄に変数を置いており、そこにRDSのドメインが入る。

- name: Configure Apache Setting
  template:
    src: phpMyAdmin.conf
    dest: "{{ apache_phpmyadmin_setting_path }}"
    owner: root
    group: root
    mode: 0644

- name: Configure phpMyAdmin Setting
  template:
    src: config.inc.php
    dest: "{{ phpmyadmin_setting_path }}"
    owner: root
    group: root
    mode: 0644
