---
###1:yum.yml
#yumでインストールものをインストール
#Apache PHP phpMyAdmin
#PHPの設定をおこなう。

#Apacheのインストール
- name: "Install Apache"
  yum:
    name: httpd
    state: latest

- name: Enable to install PHP.
  shell: "amazon-linux-extras enable php7.4"
  changed_when: False

- name: Install PHP.
  yum:
    name: php
    enablerepo: amzn2extra-php7.4
    state: present

#phpMyAdminのインストール
- name: "Install phpMyAdmin"
  yum:
    name: phpmyadmin
    state: latest
    enablerepo: remi
