---

#タイムゾーンを変更する
- name: Set Timezone
  timezone:
    name: "{{ common.timezone }}"

#YUMのアップデートを行う。
- name: Configure / Update Yum Packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

#EPELレポジトリのダウンロード
- name: Get EPEL Repository
  yum:
    name: "{{ common.repo.epel_url }}"
    state: present

#Remiレポジトリのタウンロード
- name: Get Remi Repository
  yum:
    name: "{{ common.repo.remi_url }}"
    state: present
